backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "donnees"
    label: "Données du site"
    files:
      - file: "courses.json"
        label: "Liste des courses"
        name: "liste_courses"
        format: "json"
        fields:
          - name: "courses"
            label: "Mes Courses"
            widget: "list"
            summary: "{{fields.nom}} ({{fields.dist}}km)"
            fields:
              - { label: "Année (ex: 2024)", name: "annee", widget: "number", value_type: "int" }
              - { label: "Date (ex: 15 juin 2024)", name: "date", widget: "string" }
              - { label: "Nom de la course", name: "nom", widget: "string" }
              - { label: "Lieu", name: "lieu", widget: "string" }
              - { label: "Type", name: "type", widget: "select", options: ["Trail", "Route"] }
              - { label: "Distance (km)", name: "dist", widget: "number", value_type: "int" }
              - { label: "Dénivelé D+", name: "dplus", widget: "number", value_type: "int", required: false }
              - { label: "Temps chrono", name: "temps", widget: "string" }
              - { label: "Classement général", name: "classement", widget: "number", value_type: "int" }
              - { label: "Nombre de participants", name: "participants", widget: "number", value_type: "int" }
              - { label: "Catégorie (ex: M0)", name: "cat", widget: "string" }
              - { label: "Classement catégorie", name: "classementCat", widget: "number", value_type: "int" }
